// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Repositories;

#nullable disable

namespace StoreApp.UI.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    partial class RepositoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("StoreApp.Entites.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 4,
                            Price = 0m,
                            ProductName = "deneme2"
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 0m,
                            ProductName = "deneme3"
                        },
                        new
                        {
                            ProductId = 6,
                            Price = 0m,
                            ProductName = "deneme4"
                        },
                        new
                        {
                            ProductId = 7,
                            Price = 0m,
                            ProductName = "deneme5"
                        },
                        new
                        {
                            ProductId = 8,
                            Price = 0m,
                            ProductName = "deneme6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
